### ISSUE TITLE
[Pergunta] Separador no script scraper_alesp_funcionarios.py

### ISSUE THREAD

**Issue by jtemporal** [rodolfo-viana/caecus#1]
Algum motivo especial para o [separador do csv no script scraper_alesp_funcionarios.py](https://github.com/rodolfo-viana/caecus/blob/92c57600c31dd87e994a58f48fcb2aaa3b4b5ef9/scripts/scraper_alesp_funcionarios.py#L39) ser um `;` e não uma `,`?

**Comment by rodolfo-viana** [comment]
Sim. Em breve vou alterar o código para juntar o valor dos salários dos funcionários no mesmo dataframe -- e, consequentemente, no mesmo `.csv`. Não vi ainda se os valores estão com `.` ou `,` na fração. Para já prevenir erros, usei ';', mas estou aberto a sugestões. :)

**Comment by rodolfo-viana** [comment]
Vou fechar essa issue, mas se tiver sugestão é só mandar. <3

**Comment by jtemporal** [comment]
um jeito é tratar o caso das vírgulas/pontos antes de escrever no csv usando `.replace(',','.')`.
